spring:
  application:
    name: Recallify

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&tcpKeepAlive=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 60000
      max-lifetime: 1800000
      data-source-properties:
        useServerPrepStmts: false
        cachePrepStmts: false
        reWriteBatchedInserts: true

  gemini:
    api-key: ${GEMINI_API_KEY}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 80MB
      max-request-size: 80MB

  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: ${PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG
